Airline Passenger Satisfaction Data Analysis

This project is about Analysing the customer satisfaction level at different levels like "Baggage Handling, Checkin Service, Inflight Service, etc." 
I used Pandas, Numpy, Matplotlib..

Loading--> cleaning--> handling duplicates--> handling missing values--> Identifying the patterns in the data -->Detecting Outliers in the data -->Performing Data Visualization

In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
data = pd.read_csv(r"D:\firefox downloads\test1.csv\test.csv")

In [4]:
data

,Unnamed: 0,id,Gender,Customer Type,Age,Type of Travel,Class,Flight Distance,Inflight wifi service,Departure/Arrival time convenient,...,Inflight entertainment,On-board service,Leg room service,Baggage handling,Checkin service,Inflight service,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes,satisfaction
0,0,19556,Female,Loyal Customer,52,Business travel,Eco,160,5,4,...,5,5,5,5,2,5,5,50,44.0,satisfied
1,1,90035,Female,Loyal Customer,36,Business travel,Business,2863,1,1,...,4,4,4,4,3,4,5,0,0.0,satisfied
2,2,12360,Male,disloyal Customer,20,Business travel,Eco,192,2,0,...,2,4,1,3,2,2,2,0,0.0,neutral or dissatisfied
3,3,77959,Male,Loyal Customer,44,Business travel,Business,3377,0,0,...,1,1,1,1,3,1,4,0,6.0,satisfied
4,4,36875,Female,Loyal Customer,49,Business travel,Eco,1182,2,3,...,2,2,2,2,4,2,4,0,20.0,satisfied
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25971,25971,78463,Male,disloyal Customer,34,Business travel,Business,526,3,3,...,4,3,2,4,4,5,4,0,0.0,neutral or dissatisfied
25972,25972,71167,Male,Loyal Customer,23,Business travel,Business,646,4,4,...,4,4,5,5,5,5,4,0,0.0,satisfied
25973,25973,37675,Female,Loyal Customer,17,Personal Travel,Eco,828,2,5,...,2,4,3,4,5,4,2,0,0.0,neutral or dissatisfied
25974,25974,90086,Male,Loyal Customer,14,Business travel,Business,1127,3,3,...,4,3,2,5,4,5,4,0,0.0,satisfied
25975,25975,34799,Female,Loyal Customer,42,Personal Travel,Eco,264,2,5,...,1,1,2,1,1,1,1,0,0.0,neutral or dissatisfied

In [5]:
# Finding the table info such as data type, column name, etc
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25976 entries, 0 to 25975
Data columns (total 25 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Unnamed: 0                         25976 non-null  int64
 1   id                                 25976 non-null  int64
 2   Gender                             25976 non-null  object
 3   Customer Type                      25976 non-null  object
 4   Age                                25976 non-null  int64
 5   Type of Travel                     25976 non-null  object
 6   Class                              25976 non-null  object
 7   Flight Distance                    25976 non-null  int64
 8   Inflight wifi service              25976 non-null  int64
 9   Departure/Arrival time convenient  25976 non-null  int64
 10  Ease of Online booking             25976 non-null  int64
 11  Gate location                      25976 non-null  int64
 12  Food and drink                     25976 non-null  int64
 13  Online boarding                    25976 non-null  int64
 14  Seat comfort                       25976 non-null  int64
 15  Inflight entertainment             25976 non-null  int64
 16  On-board service                   25976 non-null  int64
 17  Leg room service                   25976 non-null  int64
 18  Baggage handling                   25976 non-null  int64
 19  Checkin service                    25976 non-null  int64
 20  Inflight service                   25976 non-null  int64
 21  Cleanliness                        25976 non-null  int64
 22  Departure Delay in Minutes         25976 non-null  int64
 23  Arrival Delay in Minutes           25893 non-null  float64
 24  satisfaction                       25976 non-null  object
dtypes: float64(1), int64(19), object(5)
memory usage: 5.0+ MB

In [6]:
# Finding the Shape of the table(data)
data.shape

(25976, 25)

In [7]:
# Finding the Top 10 rows in the table
data.head(10)

,Unnamed: 0,id,Gender,Customer Type,Age,Type of Travel,Class,Flight Distance,Inflight wifi service,Departure/Arrival time convenient,...,Inflight entertainment,On-board service,Leg room service,Baggage handling,Checkin service,Inflight service,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes,satisfaction
0,0,19556,Female,Loyal Customer,52,Business travel,Eco,160,5,4,...,5,5,5,5,2,5,5,50,44.0,satisfied
1,1,90035,Female,Loyal Customer,36,Business travel,Business,2863,1,1,...,4,4,4,4,3,4,5,0,0.0,satisfied
2,2,12360,Male,disloyal Customer,20,Business travel,Eco,192,2,0,...,2,4,1,3,2,2,2,0,0.0,neutral or dissatisfied
3,3,77959,Male,Loyal Customer,44,Business travel,Business,3377,0,0,...,1,1,1,1,3,1,4,0,6.0,satisfied
4,4,36875,Female,Loyal Customer,49,Business travel,Eco,1182,2,3,...,2,2,2,2,4,2,4,0,20.0,satisfied
5,5,39177,Male,Loyal Customer,16,Business travel,Eco,311,3,3,...,5,4,3,1,1,2,5,0,0.0,satisfied
6,6,79433,Female,Loyal Customer,77,Business travel,Business,3987,5,5,...,5,5,5,5,4,5,3,0,0.0,satisfied
7,7,97286,Female,Loyal Customer,43,Business travel,Business,2556,2,2,...,4,4,4,4,5,4,3,77,65.0,satisfied
8,8,27508,Male,Loyal Customer,47,Business travel,Eco,556,5,2,...,5,2,2,5,3,3,5,1,0.0,satisfied
9,9,62482,Female,Loyal Customer,46,Business travel,Business,1744,2,2,...,4,4,4,4,5,4,4,28,14.0,satisfied

In [8]:
# Finding the bottom 10 rows in the Table
data.tail(10)

,Unnamed: 0,id,Gender,Customer Type,Age,Type of Travel,Class,Flight Distance,Inflight wifi service,Departure/Arrival time convenient,...,Inflight entertainment,On-board service,Leg room service,Baggage handling,Checkin service,Inflight service,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes,satisfaction
25966,25966,30263,Male,disloyal Customer,42,Business travel,Eco,1024,4,4,...,3,3,1,2,2,3,3,0,17.0,neutral or dissatisfied
25967,25967,90347,Female,disloyal Customer,39,Business travel,Business,404,1,1,...,2,5,3,4,4,4,2,0,0.0,neutral or dissatisfied
25968,25968,86816,Male,Loyal Customer,41,Business travel,Eco,692,2,2,...,2,2,3,3,2,3,2,15,3.0,neutral or dissatisfied
25969,25969,120654,Male,Loyal Customer,52,Business travel,Business,280,3,3,...,4,4,4,4,3,4,3,0,0.0,satisfied
25970,25970,25309,Female,disloyal Customer,36,Business travel,Eco,432,1,5,...,4,5,2,5,2,3,4,0,0.0,neutral or dissatisfied
25971,25971,78463,Male,disloyal Customer,34,Business travel,Business,526,3,3,...,4,3,2,4,4,5,4,0,0.0,neutral or dissatisfied
25972,25972,71167,Male,Loyal Customer,23,Business travel,Business,646,4,4,...,4,4,5,5,5,5,4,0,0.0,satisfied
25973,25973,37675,Female,Loyal Customer,17,Personal Travel,Eco,828,2,5,...,2,4,3,4,5,4,2,0,0.0,neutral or dissatisfied
25974,25974,90086,Male,Loyal Customer,14,Business travel,Business,1127,3,3,...,4,3,2,5,4,5,4,0,0.0,satisfied
25975,25975,34799,Female,Loyal Customer,42,Personal Travel,Eco,264,2,5,...,1,1,2,1,1,1,1,0,0.0,neutral or dissatisfied

In [9]:
# Random 10 records from table

data.sample(10)

,Unnamed: 0,id,Gender,Customer Type,Age,Type of Travel,Class,Flight Distance,Inflight wifi service,Departure/Arrival time convenient,...,Inflight entertainment,On-board service,Leg room service,Baggage handling,Checkin service,Inflight service,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes,satisfaction
10172,10172,26577,Male,disloyal Customer,23,Business travel,Eco,515,2,4,...,1,4,4,3,3,5,1,0,0.0,neutral or dissatisfied
24790,24790,123609,Female,Loyal Customer,49,Business travel,Business,1773,4,4,...,2,2,2,2,3,2,3,0,0.0,satisfied
817,817,28871,Female,disloyal Customer,22,Business travel,Eco,605,0,0,...,4,2,3,5,1,3,4,0,0.0,satisfied
22581,22581,26851,Male,Loyal Customer,61,Personal Travel,Eco,224,5,5,...,4,4,2,4,3,4,4,0,0.0,satisfied
2883,2883,44248,Female,Loyal Customer,23,Business travel,Business,359,2,2,...,4,3,5,4,3,2,4,0,0.0,satisfied
989,989,92116,Male,Loyal Customer,61,Personal Travel,Eco,1532,2,1,...,2,2,5,4,1,3,2,0,0.0,neutral or dissatisfied
14489,14489,102799,Female,disloyal Customer,24,Business travel,Eco,342,2,5,...,4,3,2,5,4,5,4,0,0.0,neutral or dissatisfied
6258,6258,37545,Female,disloyal Customer,23,Business travel,Eco,1076,2,2,...,5,2,2,3,3,4,5,0,0.0,neutral or dissatisfied
2016,2016,40410,Female,Loyal Customer,43,Business travel,Business,2920,4,4,...,5,5,5,4,1,5,5,0,0.0,satisfied
11968,11968,41855,Female,disloyal Customer,24,Business travel,Eco,483,3,4,...,5,1,1,3,2,3,5,0,0.0,neutral or dissatisfied

In [10]:
data.describe()

,Unnamed: 0,id,Age,Flight Distance,Inflight wifi service,Departure/Arrival time convenient,Ease of Online booking,Gate location,Food and drink,Online boarding,Seat comfort,Inflight entertainment,On-board service,Leg room service,Baggage handling,Checkin service,Inflight service,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes
count,25976.000000,25976.000000,25976.000000,25976.000000,25976.000000,25976.000000,25976.000000,25976.000000,25976.000000,25976.000000,25976.000000,25976.000000,25976.000000,25976.000000,25976.000000,25976.000000,25976.000000,25976.000000,25976.00000,25893.000000
mean,12987.500000,65005.657992,39.620958,1193.788459,2.724746,3.046812,2.756775,2.977094,3.215353,3.261665,3.449222,3.357753,3.385664,3.350169,3.633238,3.314175,3.649253,3.286226,14.30609,14.740857
std,7498.769632,37611.526647,15.135685,998.683999,1.335384,1.533371,1.412951,1.282133,1.331506,1.355536,1.320090,1.338299,1.282088,1.318862,1.176525,1.269332,1.180681,1.319330,37.42316,37.517539
min,0.000000,17.000000,7.000000,31.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.00000,0.000000
25%,6493.750000,32170.500000,27.000000,414.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,3.000000,3.000000,3.000000,2.000000,0.00000,0.000000
50%,12987.500000,65319.500000,40.000000,849.000000,3.000000,3.000000,3.000000,3.000000,3.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,3.000000,4.000000,3.000000,0.00000,0.000000
75%,19481.250000,97584.250000,51.000000,1744.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,5.000000,4.000000,4.000000,4.000000,5.000000,4.000000,5.000000,4.000000,12.00000,13.000000
max,25975.000000,129877.000000,85.000000,4983.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,1128.00000,1115.000000

In [11]:
data.select_dtypes(include = np.int64)

,Unnamed: 0,id,Age,Flight Distance,Inflight wifi service,Departure/Arrival time convenient,Ease of Online booking,Gate location,Food and drink,Online boarding,Seat comfort,Inflight entertainment,On-board service,Leg room service,Baggage handling,Checkin service,Inflight service,Cleanliness,Departure Delay in Minutes
0,0,19556,52,160,5,4,3,4,3,4,3,5,5,5,5,2,5,5,50
1,1,90035,36,2863,1,1,3,1,5,4,5,4,4,4,4,3,4,5,0
2,2,12360,20,192,2,0,2,4,2,2,2,2,4,1,3,2,2,2,0
3,3,77959,44,3377,0,0,0,2,3,4,4,1,1,1,1,3,1,4,0
4,4,36875,49,1182,2,3,4,3,4,1,2,2,2,2,2,4,2,4,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25971,25971,78463,34,526,3,3,3,1,4,3,4,4,3,2,4,4,5,4,0
25972,25972,71167,23,646,4,4,4,4,4,4,4,4,4,5,5,5,5,4,0
25973,25973,37675,17,828,2,5,1,5,2,1,2,2,4,3,4,5,4,2,0
25974,25974,90086,14,1127,3,3,3,3,4,4,4,4,3,2,5,4,5,4,0
25975,25975,34799,42,264,2,5,2,5,4,2,2,1,1,2,1,1,1,1,0

In [12]:
data.select_dtypes(include = 'object')

,Gender,Customer Type,Type of Travel,Class,satisfaction
0,Female,Loyal Customer,Business travel,Eco,satisfied
1,Female,Loyal Customer,Business travel,Business,satisfied
2,Male,disloyal Customer,Business travel,Eco,neutral or dissatisfied
3,Male,Loyal Customer,Business travel,Business,satisfied
4,Female,Loyal Customer,Business travel,Eco,satisfied
...,...,...,...,...,...
25971,Male,disloyal Customer,Business travel,Business,neutral or dissatisfied
25972,Male,Loyal Customer,Business travel,Business,satisfied
25973,Female,Loyal Customer,Personal Travel,Eco,neutral or dissatisfied
25974,Male,Loyal Customer,Business travel,Business,satisfied
25975,Female,Loyal Customer,Personal Travel,Eco,neutral or dissatisfied

In [13]:
# Finding the "NULL VALUES" count in each column in the table
data.isna().sum()

Unnamed: 0                            0
id                                    0
Gender                                0
Customer Type                         0
Age                                   0
Type of Travel                        0
Class                                 0
Flight Distance                       0
Inflight wifi service                 0
Departure/Arrival time convenient     0
Ease of Online booking                0
Gate location                         0
Food and drink                        0
Online boarding                       0
Seat comfort                          0
Inflight entertainment                0
On-board service                      0
Leg room service                      0
Baggage handling                      0
Checkin service                       0
Inflight service                      0
Cleanliness                           0
Departure Delay in Minutes            0
Arrival Delay in Minutes             83
satisfaction                          0
dtype: int64

In [14]:
# Finding the unique values in the "Arrival Delay in Minutes" column
data["Arrival Delay in Minutes"].unique()

array([4.400e+01, 0.000e+00, 6.000e+00, 2.000e+01, 6.500e+01, 1.400e+01,
       1.900e+01, 7.000e+00, 1.130e+02, 2.000e+00, 4.900e+01, 1.300e+01,
       6.800e+01, 1.000e+00, 7.000e+01, 1.200e+01, 1.000e+01, 4.000e+00,
       1.770e+02, 3.000e+00, 5.500e+01, 9.000e+01, 3.200e+01, 4.600e+01,
       5.700e+01, 4.700e+01, 4.000e+01, 2.400e+01, 2.700e+01, 5.200e+01,
       1.700e+01, 1.100e+01, 3.400e+01, 9.500e+01, 6.600e+01, 8.000e+00,
       8.600e+01, 8.800e+01, 1.780e+02, 7.800e+01, 1.800e+01, 7.200e+01,
       4.100e+01, 9.100e+01, 3.500e+01, 1.600e+01, 2.500e+01, 7.700e+01,
       9.400e+01, 1.630e+02, 1.020e+02, 4.200e+01, 1.500e+01, 9.000e+00,
       8.500e+01, 2.300e+01, 2.800e+01, 3.000e+01, 7.100e+01, 5.000e+00,
       7.900e+01, 2.510e+02, 1.510e+02, 3.800e+01, 6.200e+01, 2.100e+01,
       2.900e+01, 9.300e+01, 2.320e+02, 1.560e+02, 1.170e+02, 2.600e+01,
       5.100e+01, 9.900e+01, 1.210e+02, 7.500e+01, 6.300e+01, 9.200e+01,
       4.500e+01, 1.230e+02, 1.290e+02, 8.400e+01,       nan, 2.100e+02,
       1.000e+02, 2.200e+01, 5.800e+01, 1.470e+02, 6.100e+01, 2.750e+02,
       1.190e+02, 4.850e+02, 6.000e+01, 3.100e+01, 3.360e+02, 1.280e+02,
       4.800e+01, 9.700e+01, 6.900e+01, 5.900e+01, 5.000e+01, 4.070e+02,
       5.400e+01, 4.300e+01, 1.010e+02, 3.700e+01, 9.600e+01, 1.050e+02,
       8.200e+01, 1.140e+02, 1.380e+02, 1.910e+02, 3.300e+01, 2.860e+02,
       1.220e+02, 1.030e+02, 8.000e+01, 5.300e+01, 6.400e+01, 7.300e+01,
       1.710e+02, 1.240e+02, 1.090e+02, 5.600e+01, 1.150e+02, 8.700e+01,
       3.600e+01, 2.210e+02, 1.600e+02, 2.400e+02, 2.480e+02, 1.390e+02,
       1.970e+02, 1.040e+02, 1.550e+02, 2.470e+02, 7.600e+01, 6.700e+01,
       3.900e+01, 2.070e+02, 9.400e+02, 8.300e+01, 1.810e+02, 2.050e+02,
       2.010e+02, 2.620e+02, 9.800e+01, 1.620e+02, 1.110e+02, 2.850e+02,
       1.940e+02, 1.400e+02, 2.990e+02, 2.960e+02, 1.250e+02, 1.490e+02,
       1.480e+02, 1.330e+02, 1.350e+02, 1.060e+02, 1.310e+02, 2.110e+02,
       1.430e+02, 1.420e+02, 1.070e+02, 2.030e+02, 7.400e+01, 1.790e+02,
       8.100e+01, 3.470e+02, 2.000e+02, 2.040e+02, 1.880e+02, 1.760e+02,
       1.410e+02, 3.440e+02, 8.900e+01, 1.340e+02, 1.840e+02, 1.360e+02,
       1.100e+02, 1.200e+02, 1.580e+02, 1.740e+02, 2.360e+02, 1.440e+02,
       1.850e+02, 1.720e+02, 1.180e+02, 1.500e+02, 3.740e+02, 1.080e+02,
       1.270e+02, 1.640e+02, 1.160e+02, 2.430e+02, 1.370e+02, 1.730e+02,
       2.530e+02, 1.120e+02, 3.060e+02, 2.920e+02, 1.670e+02, 3.120e+02,
       2.250e+02, 3.810e+02, 2.090e+02, 2.170e+02, 2.240e+02, 1.260e+02,
       1.650e+02, 1.860e+02, 1.820e+02, 2.230e+02, 4.010e+02, 1.590e+02,
       2.800e+02, 2.610e+02, 2.350e+02, 4.910e+02, 1.660e+02, 4.130e+02,
       1.830e+02, 1.980e+02, 2.650e+02, 1.690e+02, 1.890e+02, 4.380e+02,
       2.780e+02, 1.990e+02, 3.880e+02, 2.310e+02, 2.220e+02, 1.320e+02,
       2.710e+02, 3.250e+02, 1.900e+02, 2.810e+02, 1.610e+02, 2.590e+02,
       3.030e+02, 1.540e+02, 2.120e+02, 1.570e+02, 2.390e+02, 7.950e+02,
       2.080e+02, 2.180e+02, 1.530e+02, 1.680e+02, 1.450e+02, 2.130e+02,
       1.520e+02, 3.070e+02, 4.020e+02, 3.040e+02, 1.300e+02, 1.870e+02,
       2.440e+02, 2.150e+02, 6.080e+02, 3.130e+02, 1.800e+02, 4.000e+02,
       3.580e+02, 2.450e+02, 3.010e+02, 4.030e+02, 2.270e+02, 3.680e+02,
       4.930e+02, 2.890e+02, 4.730e+02, 3.490e+02, 2.370e+02, 3.170e+02,
       1.920e+02, 3.160e+02, 1.115e+03, 1.960e+02, 1.700e+02, 2.410e+02,
       2.020e+02, 2.380e+02, 3.200e+02, 2.140e+02, 8.220e+02, 1.750e+02,
       4.100e+02, 5.800e+02, 3.570e+02, 2.910e+02, 6.150e+02, 1.930e+02,
       1.460e+02, 3.500e+02, 2.290e+02, 2.540e+02, 3.720e+02, 2.420e+02,
       5.430e+02, 2.550e+02, 2.190e+02, 2.760e+02, 7.480e+02, 5.860e+02,
       2.730e+02, 3.330e+02, 2.720e+02, 2.520e+02, 3.300e+02, 2.790e+02,
       2.200e+02, 3.190e+02, 3.050e+02, 2.500e+02, 2.770e+02, 2.460e+02,
       2.330e+02, 3.110e+02, 2.880e+02])

In [15]:
# Finding the mean and round the mean for the column "Arrival Delay in Minutes"
data["Arrival Delay in Minutes"].mean().round()

np.float64(15.0)

In [16]:
# Changing the data type for the column "Arrival Delay in Minutes" from "FLOAT TO INTEGER" and replacing "NULL VALUES " with mean round
data["Arrival Delay in Minutes"] = data["Arrival Delay in Minutes"].fillna(data["Arrival Delay in Minutes"].mean().round()).astype(int)

In [17]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25976 entries, 0 to 25975
Data columns (total 25 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Unnamed: 0                         25976 non-null  int64
 1   id                                 25976 non-null  int64
 2   Gender                             25976 non-null  object
 3   Customer Type                      25976 non-null  object
 4   Age                                25976 non-null  int64
 5   Type of Travel                     25976 non-null  object
 6   Class                              25976 non-null  object
 7   Flight Distance                    25976 non-null  int64
 8   Inflight wifi service              25976 non-null  int64
 9   Departure/Arrival time convenient  25976 non-null  int64
 10  Ease of Online booking             25976 non-null  int64
 11  Gate location                      25976 non-null  int64
 12  Food and drink                     25976 non-null  int64
 13  Online boarding                    25976 non-null  int64
 14  Seat comfort                       25976 non-null  int64
 15  Inflight entertainment             25976 non-null  int64
 16  On-board service                   25976 non-null  int64
 17  Leg room service                   25976 non-null  int64
 18  Baggage handling                   25976 non-null  int64
 19  Checkin service                    25976 non-null  int64
 20  Inflight service                   25976 non-null  int64
 21  Cleanliness                        25976 non-null  int64
 22  Departure Delay in Minutes         25976 non-null  int64
 23  Arrival Delay in Minutes           25976 non-null  int64
 24  satisfaction                       25976 non-null  object
dtypes: int64(20), object(5)
memory usage: 5.0+ MB

In [18]:
# verfying the whether the null values are replaced are not..
data.isna().sum()

Unnamed: 0                           0
id                                   0
Gender                               0
Customer Type                        0
Age                                  0
Type of Travel                       0
Class                                0
Flight Distance                      0
Inflight wifi service                0
Departure/Arrival time convenient    0
Ease of Online booking               0
Gate location                        0
Food and drink                       0
Online boarding                      0
Seat comfort                         0
Inflight entertainment               0
On-board service                     0
Leg room service                     0
Baggage handling                     0
Checkin service                      0
Inflight service                     0
Cleanliness                          0
Departure Delay in Minutes           0
Arrival Delay in Minutes             0
satisfaction                         0
dtype: int64

In [19]:
# Finding the duplicate values in the data table
data[data.duplicated()]

Empty DataFrame
Columns: [Unnamed: 0, id, Gender, Customer Type, Age, Type of Travel, Class, Flight Distance, Inflight wifi service, Departure/Arrival time convenient, Ease of Online booking, Gate location, Food and drink, Online boarding, Seat comfort, Inflight entertainment, On-board service, Leg room service, Baggage handling, Checkin service, Inflight service, Cleanliness, Departure Delay in Minutes, Arrival Delay in Minutes, satisfaction]
Index: []

[0 rows x 25 columns]

In [20]:
data

,Unnamed: 0,id,Gender,Customer Type,Age,Type of Travel,Class,Flight Distance,Inflight wifi service,Departure/Arrival time convenient,...,Inflight entertainment,On-board service,Leg room service,Baggage handling,Checkin service,Inflight service,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes,satisfaction
0,0,19556,Female,Loyal Customer,52,Business travel,Eco,160,5,4,...,5,5,5,5,2,5,5,50,44,satisfied
1,1,90035,Female,Loyal Customer,36,Business travel,Business,2863,1,1,...,4,4,4,4,3,4,5,0,0,satisfied
2,2,12360,Male,disloyal Customer,20,Business travel,Eco,192,2,0,...,2,4,1,3,2,2,2,0,0,neutral or dissatisfied
3,3,77959,Male,Loyal Customer,44,Business travel,Business,3377,0,0,...,1,1,1,1,3,1,4,0,6,satisfied
4,4,36875,Female,Loyal Customer,49,Business travel,Eco,1182,2,3,...,2,2,2,2,4,2,4,0,20,satisfied
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25971,25971,78463,Male,disloyal Customer,34,Business travel,Business,526,3,3,...,4,3,2,4,4,5,4,0,0,neutral or dissatisfied
25972,25972,71167,Male,Loyal Customer,23,Business travel,Business,646,4,4,...,4,4,5,5,5,5,4,0,0,satisfied
25973,25973,37675,Female,Loyal Customer,17,Personal Travel,Eco,828,2,5,...,2,4,3,4,5,4,2,0,0,neutral or dissatisfied
25974,25974,90086,Male,Loyal Customer,14,Business travel,Business,1127,3,3,...,4,3,2,5,4,5,4,0,0,satisfied
25975,25975,34799,Female,Loyal Customer,42,Personal Travel,Eco,264,2,5,...,1,1,2,1,1,1,1,0,0,neutral or dissatisfied

In [21]:
data.shape

(25976, 25)

In [22]:
# Dropping the unwanted columns 
data = data.drop("Unnamed: 0",axis = 1)

In [23]:
data.shape

(25976, 24)

In [24]:
data

,id,Gender,Customer Type,Age,Type of Travel,Class,Flight Distance,Inflight wifi service,Departure/Arrival time convenient,Ease of Online booking,...,Inflight entertainment,On-board service,Leg room service,Baggage handling,Checkin service,Inflight service,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes,satisfaction
0,19556,Female,Loyal Customer,52,Business travel,Eco,160,5,4,3,...,5,5,5,5,2,5,5,50,44,satisfied
1,90035,Female,Loyal Customer,36,Business travel,Business,2863,1,1,3,...,4,4,4,4,3,4,5,0,0,satisfied
2,12360,Male,disloyal Customer,20,Business travel,Eco,192,2,0,2,...,2,4,1,3,2,2,2,0,0,neutral or dissatisfied
3,77959,Male,Loyal Customer,44,Business travel,Business,3377,0,0,0,...,1,1,1,1,3,1,4,0,6,satisfied
4,36875,Female,Loyal Customer,49,Business travel,Eco,1182,2,3,4,...,2,2,2,2,4,2,4,0,20,satisfied
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25971,78463,Male,disloyal Customer,34,Business travel,Business,526,3,3,3,...,4,3,2,4,4,5,4,0,0,neutral or dissatisfied
25972,71167,Male,Loyal Customer,23,Business travel,Business,646,4,4,4,...,4,4,5,5,5,5,4,0,0,satisfied
25973,37675,Female,Loyal Customer,17,Personal Travel,Eco,828,2,5,1,...,2,4,3,4,5,4,2,0,0,neutral or dissatisfied
25974,90086,Male,Loyal Customer,14,Business travel,Business,1127,3,3,3,...,4,3,2,5,4,5,4,0,0,satisfied
25975,34799,Female,Loyal Customer,42,Personal Travel,Eco,264,2,5,2,...,1,1,2,1,1,1,1,0,0,neutral or dissatisfied

In [25]:
# Finding the all columns names in the table
data.columns

Index(['id', 'Gender', 'Customer Type', 'Age', 'Type of Travel', 'Class',
       'Flight Distance', 'Inflight wifi service',
       'Departure/Arrival time convenient', 'Ease of Online booking',
       'Gate location', 'Food and drink', 'Online boarding', 'Seat comfort',
       'Inflight entertainment', 'On-board service', 'Leg room service',
       'Baggage handling', 'Checkin service', 'Inflight service',
       'Cleanliness', 'Departure Delay in Minutes', 'Arrival Delay in Minutes',
       'satisfaction'],
      dtype='object')

In [26]:
data.columns = data.columns.str.strip()

In [27]:
# Finding the unique values and how many unique values are there in the column "Customer Type" 

print(data["Customer Type"].unique())
print(len(data["Customer Type"].unique()))

['Loyal Customer' 'disloyal Customer']
2

In [28]:
# Finding the unique values and how many uniquw values are there in the column "Type of Travel"

print(data['Type of Travel'].unique())
print(len(data['Type of Travel'].unique()))

['Business travel' 'Personal Travel']
2

In [29]:
# # Finding the unique values and how many uniquw values are there in the column "Class"

print(data['Class'].unique())
print(len(data['Class'].unique()))

['Eco' 'Business' 'Eco Plus']
3

In [30]:
# # Finding the unique values and how many uniquw values are there in the column "Age"

print(data['Age'].unique())
print(len(data['Age'].unique()))

[52 36 20 44 49 16 77 43 47 46 33 60 50 31 55 25 30 62 24 22 51 56 41 53
 12 39 32 40 42 28 59 58 27 67 70 66 19 69 35 54 26 61 21 37 45 38  7 34
 17 15 48 13 11 29  8 18 23 65 57 80 64  9 14 68 10 79 63 73 74 71 72 76
 78 75 85]
75

In [31]:
# Removing unusal spaces in the data set for string objects using lambda function..

col = ['Gender','Customer Type','Type of Travel','Class','satisfaction']

data[col]= data[col].apply(lambda x:x.str.strip())

In [32]:
# Finding the How many Male and Female passenger by using "Value_counts"
data['Gender'].value_counts()

Gender
Female    13172
Male      12804
Name: count, dtype: int64

In [33]:
# Analyzing the Number of Loyal and Disloyal Customers Using Value Counts

data['Customer Type'].value_counts()

Customer Type
Loyal Customer       21177
disloyal Customer     4799
Name: count, dtype: int64

In [34]:
# Analyzing Passenger Travel Distribution by Business and Personal Travel

data['Type of Travel'].value_counts()

Type of Travel
Business travel    18038
Personal Travel     7938
Name: count, dtype: int64

In [35]:
# Analyzing number of passagers are traveling in Business, Eco, Eco Plus 

data['Class'].value_counts()

Class
Business    12495
Eco         11564
Eco Plus     1917
Name: count, dtype: int64

In [36]:
# Analysing Number of passagers Satisfaction level 

data['satisfaction'].value_counts()

satisfaction
neutral or dissatisfied    14573
satisfied                  11403
Name: count, dtype: int64

In [37]:
data.loc[0:4][['id','Gender','Age']]

      id  Gender  Age
0  19556  Female   52
1  90035  Female   36
2  12360    Male   20
3  77959    Male   44
4  36875  Female   49

In [38]:
data.iloc[0:4],['id','Gender','Age']

(      id  Gender      Customer Type  Age   Type of Travel     Class  \
 0  19556  Female     Loyal Customer   52  Business travel       Eco
 1  90035  Female     Loyal Customer   36  Business travel  Business
 2  12360    Male  disloyal Customer   20  Business travel       Eco
 3  77959    Male     Loyal Customer   44  Business travel  Business

    Flight Distance  Inflight wifi service  Departure/Arrival time convenient  \
 0              160                      5                                  4
 1             2863                      1                                  1
 2              192                      2                                  0
 3             3377                      0                                  0

    Ease of Online booking  ...  Inflight entertainment  On-board service  \
 0                       3  ...                       5                 5
 1                       3  ...                       4                 4
 2                       2  ...                       2                 4
 3                       0  ...                       1                 1

    Leg room service  Baggage handling  Checkin service  Inflight service  \
 0                 5                 5                2                 5
 1                 4                 4                3                 4
 2                 1                 3                2                 2
 3                 1                 1                3                 1

    Cleanliness  Departure Delay in Minutes  Arrival Delay in Minutes  \
 0            5                          50                        44
 1            5                           0                         0
 2            2                           0                         0
 3            4                           0                         6

               satisfaction
 0                satisfied
 1                satisfied
 2  neutral or dissatisfied
 3                satisfied

 [4 rows x 24 columns],
 ['id', 'Gender', 'Age'])

In [39]:
data.iloc[0:4,0:5]

      id  Gender      Customer Type  Age   Type of Travel
0  19556  Female     Loyal Customer   52  Business travel
1  90035  Female     Loyal Customer   36  Business travel
2  12360    Male  disloyal Customer   20  Business travel
3  77959    Male     Loyal Customer   44  Business travel

In [40]:
data['Age'].max()

85

In [41]:
data['Age'].min()

7

# Flitering the Data

In [42]:
# Adding new column by grouping age

bins = [0,10, 20, 30, 40, 50, 60, 70, 80,90, 100]
labels = ["1-10", "11-20", "21-30", "31-40", "41-50",
          "51-60", "61-70", "71-80", "81-90",
          "91-100"]

data['Age_group']= pd.cut(data['Age'], bins=bins, labels=labels)

In [43]:
data[['Age_group','Age']].head(15)

   Age_group  Age
0      51-60   52
1      31-40   36
2      11-20   20
3      41-50   44
4      41-50   49
5      11-20   16
6      71-80   77
7      41-50   43
8      41-50   47
9      41-50   46
10     41-50   47
11     31-40   33
12     41-50   46
13     51-60   60
14     51-60   52

In [44]:
data.shape

(25976, 25)

In [45]:
# flitering the Gender based on the Age_group 

data.groupby(['Gender','Age_group']).size()

C:\Users\balac\AppData\Local\Temp\ipykernel_17584\1101916877.py:3: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  data.groupby(['Gender','Age_group']).size()

Gender  Age_group
Female  1-10          295
        11-20        1065
        21-30        2837
        31-40        2598
        41-50        2953
        51-60        2390
        61-70         931
        71-80          98
        81-90           5
        91-100          0
Male    1-10          291
        11-20        1074
        21-30        2561
        31-40        2591
        41-50        2854
        51-60        2389
        61-70         939
        71-80         102
        81-90           3
        91-100          0
dtype: int64

In [46]:
# Analysing the number of Customer are Loyal Customer or not based on the Gender  

data.groupby(['Gender','Customer Type']).size()

Gender  Customer Type
Female  Loyal Customer       10598
        disloyal Customer     2574
Male    Loyal Customer       10579
        disloyal Customer     2225
dtype: int64

In [47]:
business = data[data['Class'] == 'Business']

In [48]:
# Analysing which Age_group passanger are more

business.groupby(['Gender','Age_group']).size()

C:\Users\balac\AppData\Local\Temp\ipykernel_17584\1603845000.py:3: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  business.groupby(['Gender','Age_group']).size()

Gender  Age_group
Female  1-10           28
        11-20         217
        21-30        1183
        31-40        1398
        41-50        1788
        51-60        1456
        61-70         198
        71-80          63
        81-90           5
        91-100          0
Male    1-10           37
        11-20         215
        21-30        1122
        31-40        1374
        41-50        1706
        51-60        1437
        61-70         209
        71-80          58
        81-90           1
        91-100          0
dtype: int64

In [49]:
# Finding the the satisfied customer based on the customer type and Gender.

satisfy_data= data[data['satisfaction'] == 'satisfied']
satisfy_data.groupby(['Customer Type','Gender']).size()

Customer Type      Gender
Loyal Customer     Female    5107
                   Male      5088
disloyal Customer  Female     628
                   Male       580
dtype: int64

In [50]:
# Filtering the customer who are traveling in the Eco Plus based on Gender and type of Travel grouping.

class_data = data[data['Class']=='Eco Plus']
class_data.groupby(['Gender','Type of Travel']).size()

Gender  Type of Travel
Female  Business travel    565
        Personal Travel    459
Male    Business travel    447
        Personal Travel    446
dtype: int64

In [51]:
# Finding the only Male.

data[(data['Class'] == 'Eco Plus') & (data['Gender'] == 'Male')].shape

(893, 25)

In [52]:
data.groupby(['Class','Gender']).size()

Class     Gender
Business  Female    6336
          Male      6159
Eco       Female    5812
          Male      5752
Eco Plus  Female    1024
          Male       893
dtype: int64

In [53]:
data.groupby('Inflight wifi service').size()

Inflight wifi service
0     813
1    4488
2    6490
3    6317
4    4981
5    2887
dtype: int64

In [54]:
# Inflight Wi-Fi Service Rating by Gender Among Satisfied Passengers

satisfy_data.groupby(['Gender','Inflight wifi service']).size()

Gender  Inflight wifi service
Female  0                         407
        1                         741
        2                         761
        3                         818
        4                        1546
        5                        1462
Male    0                         404
        1                         781
        2                         806
        3                         805
        4                        1482
        5                        1390
dtype: int64

In [55]:
data[ (data['Gender'] == 'Male')& (data['satisfaction']=='satisfied')].shape[0]

5668

In [56]:
data.groupby(['Class','Cleanliness']).size()

Class     Cleanliness
Business  1              1133
          2              1379
          3              3223
          4              3634
          5              3126
Eco       0                 1
          1              1954
          2              2210
          3              2463
          4              2692
          5              2244
Eco Plus  0                 1
          1               324
          2               392
          3               379
          4               464
          5               357
dtype: int64

In [72]:
data.columns

Index(['id', 'Gender', 'Customer Type', 'Age', 'Type of Travel', 'Class',
       'Flight Distance', 'Inflight wifi service',
       'Departure/Arrival time convenient', 'Ease of Online booking',
       'Gate location', 'Food and drink', 'Online boarding', 'Seat comfort',
       'Inflight entertainment', 'On-board service', 'Leg room service',
       'Baggage handling', 'Checkin service', 'Inflight service',
       'Cleanliness', 'Departure Delay in Minutes', 'Arrival Delay in Minutes',
       'satisfaction', 'Age_group', 'Satisfaction_Binary'],
      dtype='object')

In [81]:
data['Satisfaction_Binary'] = (
    data['satisfaction'] == 'satisfied'
).astype(int)


service_cols = [
    'Inflight wifi service',
       'Departure/Arrival time convenient', 'Ease of Online booking',
       'Gate location', 'Food and drink', 'Online boarding', 'Seat comfort',
       'Inflight entertainment', 'On-board service', 'Leg room service',
       'Baggage handling', 'Checkin service', 'Inflight service',
       'Cleanliness'
]


correlation = data[service_cols].corrwith(
    data['Satisfaction_Binary'],
    method='spearman'
).sort_values(ascending=False)

print(correlation.round(2))
print("\n")
print(correlation.idxmax())

Online boarding                      0.54
Inflight entertainment               0.40
Seat comfort                         0.36
On-board service                     0.33
Leg room service                     0.31
Cleanliness                          0.31
Inflight wifi service                0.28
Baggage handling                     0.28
Inflight service                     0.27
Checkin service                      0.24
Food and drink                       0.21
Ease of Online booking               0.16
Gate location                       -0.02
Departure/Arrival time convenient   -0.06
dtype: float64


Online boarding

In [ ]:
pd.crosstab(
    [data['Type of Travel'], data['Class']],
    data['satisfaction'],
    normalize='index'
) * 100

In [59]:
import matplotlib.pyplot as plt